vim.keymap.set('n', '<leader>wh', "<C-w>h", { noremap = true, silent = true })
vim.keymap.set('n', '<leader>wj', "<C-w>j", { noremap = true, silent = true })
vim.keymap.set('n', '<leader>wk', "<C-w>k", { noremap = true, silent = true })
vim.keymap.set('n', '<leader>wl', "<C-w>l", { noremap = true, silent = true })
vim.keymap.set('n', '<leader>bn', function() vim.api.nvim_command(':bnext') end)
vim.keymap.set('n', '<leader>bp', function() vim.api.nvim_command(':bprevious') end)
vim.keymap.set('n', '<leader>/', function()
	vim.api.nvim_command(':let @/ = ""')
	require('neominimap').refresh()
end)
vim.api.nvim_cmd({cmd = "command", args={'Bd', 'lua Snacks.bufdelete()'}}, {})
