# Hardware configuration for Razer Blade
# Generated by 'nixos-generate-config'
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.initrd.luks.devices = {
    root = { device = "/dev/disk/by-uuid/ad032932-3f84-455a-8f1e-e165c12f9e27"; };
    swap = { device = "/dev/disk/by-uuid/12f17d05-001e-46e9-b6ce-072d592fdf13"; };
    data = { device = "/dev/disk/by-uuid/772b86e5-61e0-45b2-97db-f53a5a5931c9"; };
  };
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [ "subvol=/@" "compress=zstd" "noatime" "ssd" "space_cache=v2" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [ "subvol=/@nix" "compress=zstd" "noatime" "ssd" "space_cache=v2" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [ "subvol=/@home" "compress=zstd" "noatime" "ssd" "space_cache=v2" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [ "subvol=/@log" "compress=zstd" "noatime" "ssd" "space_cache=v2" ];
      neededForBoot = true;
    };

  fileSystems."/tmp" =
    { device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [ "subvol=/@tmp" "compress=zstd" "noatime" "ssd" "space_cache=v2" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7C97-A5EE";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/data" =
    { device = "/dev/mapper/data";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" "ssd" "space_cache=v2" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/swap"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
