return {
	"nvim-treesitter/nvim-treesitter",
	event = "VeryLazy",
	build = ":TSUpdate",
	config = function ()
	local configs = require("nvim-treesitter.configs")
	  configs.setup({
	      ensure_installed = {
			"bash",
			"c",
			"cmake",
			"css",
			"elixir",
			"git_config",
			"git_rebase",
			"gitattributes",
			"gitcommit",
			"gitignore",
			"gn",
			"html",
			"javascript",
			"json",
			"lua",
			"objc",
			"powershell",
			"printf",
			"python",
			"query",
			"rust",
			"sql",
			"starlark",
			"terraform",
			"typescript",
			"tsx",
			"vim",
			"vimdoc",
			"xml",
			"yaml",
	      },
	      sync_install = false,
	      highlight = { enable = true },
	      indent = { enable = true },
	    })
	end
}
